### ISSUE TITLE
release link...

### ISSUE THREAD

**Issue by moebiussurfing** [alptugan/p5.utils#1]
hey, 
that link on the readme looks different when you are not the repo owner...
`on from ["Releases" page](https://github.com/alptugan/p5.utils/releases/download/v0.0.1/p5.utils.min.js).`

should point to:
https://github.com/alptugan/p5.utils/releases

or
https://github.com/alptugan/p5.utils/releases/download/v0.1.2/p5.utils.min.js

regards

**Comment by alptugan** [comment]
Thanks @moebiussurfing!
I've just noticed the issue. 
Fixed it.

**Comment by alptugan** [comment]
Read me file updated.
