### ISSUE TITLE
Additional option to hide/show the ruler information box in setRulerStyle function

### ISSUE THREAD

**Issue by codingepaduli** [alptugan/p5.utils#3]
Can you add another option to hide/show the ruler information box in setRulerStyle function, please?

Like in the following example:
![rulerStyle](https://user-images.githubusercontent.com/52714870/207104758-e5507f36-7541-480a-b9b5-598ddbc36b19.png)

**Comment by alptugan** [comment]
@codingepaduli it's updated. Thanks for the feedback.
Now you can enable/disable the info card as follows;


    // Set styling before the enabling the ruler
    utils.setRulerStyle(
        "rgba(200,200,200,1)", // Ruler Bg Color
        "rgba(30,30,30,1)", // Ruler Text Color
        40, // Ruler Size
        "rgba(200,200,200,1)", // Info Text Color following the mouse cursor
        "rgba(5,5,5,0.7)", // Info Text Background Color
        "rgba(255,0,0,1)", // Ticker Color that projects the mouse cursor on top and left ruler bar
        "10px monospace", // Overall font size and font family
        false // Set true or false, to hide/show info card next to mouse cursor. By default it is true.
    );
